AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Event processor for handling messages from SQS

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:
  EventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: EventQueue
      VisibilityTimeout: 300

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: src/app.lambda_handler
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EventQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          LOG_LEVEL: INFO

Outputs:
  ProcessorFunction:
    Description: "Processor Lambda Function ARN"
    Value: !GetAtt ProcessorFunction.Arn

  EventQueue:
    Description: "SQS Queue URL"
    Value: !GetAtt EventQueue.QueueUrl
