import type { Metadata } from "next";
import { Source_Code_Pro, Source_Serif_4, Work_Sans } from "next/font/google";
import "./globals.css";

const sans = Work_Sans({
  variable: "--font-sans",
  subsets: ["latin", "vietnamese"],
});

const serif = Source_Serif_4({
  variable: "--font-serif",
  subsets: ["latin", "vietnamese"],
});

const mono = Source_Code_Pro({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script>
          {'document.documentElement.setAttribute("data-theme", "dark");'}
        </script>
      </head>
      <body className={`${sans.variable} ${serif.variable} ${mono.variable}`}>
        {children}
      </body>
    </html>
  );
}
