packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
  uniforms-antd@*:
    dependencies:
      "@ant-design/icons": "^5.0.0"
      "antd": "*"
      "react": "*"
      "uniforms": "*"
      "dayjs": "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
